#!/usr/bin/env python3
"""
analyze.py -- Turn results/benchmark.csv into the speed-up and efficiency
tables used by the report.

Two speed-ups are computed, and keeping them apart is the point:

  compute speed-up  = T_seq(compute) / T_par(compute)
      How well the parallel *work* scales. This is what Amdahl's law talks
      about and it is the number that judges the decomposition.

  end-to-end speed-up = T_seq(total) / T_par(total)
      What a user actually experiences, communication and I/O included. For a
      kernel this cheap it is a much harsher number, and pretending otherwise
      would be dishonest.

Usage: python3 bench/analyze.py [results/benchmark.csv]
Writes results/analysis.md and prints the same tables.
"""
import csv
import sys
import os
from collections import defaultdict

CSV = sys.argv[1] if len(sys.argv) > 1 else "results/benchmark.csv"
OUT = os.path.join(os.path.dirname(CSV) or ".", "analysis.md")


def num(s):
    return float(s) if s not in ("", None) else 0.0


def main():
    with open(CSV) as f:
        rows = [r for r in csv.DictReader(f)]

    # rows[resolution][mode][procs] = row
    by_res = defaultdict(lambda: defaultdict(dict))
    for r in rows:
        res = f"{r['width']}x{r['height']}"
        by_res[res][r["mode"]][int(r["procs"])] = r

    out = []
    w = out.append
    w("# Measured results\n")
    w("Generated by `bench/analyze.py` from `benchmark.csv`. "
      "Times are the best of the trials, in seconds.\n")

    if os.path.exists("results/environment.txt"):
        w("```")
        w(open("results/environment.txt").read().strip())
        w("```\n")

    for res in sorted(by_res, key=lambda s: int(s.split("x")[0])):
        modes = by_res[res]
        seq = modes.get("sequential", {}).get(1)
        if not seq:
            continue
        pixels = int(seq["pixels"])
        w(f"## {res}  ({pixels/1e6:.1f} MPixel, "
          f"{pixels*3/2**20:.1f} MiB of RGB input)\n")
        w(f"Sequential baseline: compute **{num(seq['compute_s'])*1000:.3f} ms**, "
          f"end-to-end **{num(seq['total_s'])*1000:.3f} ms** "
          f"(read {num(seq['read_s'])*1000:.2f} ms, "
          f"write {num(seq['write_s'])*1000:.2f} ms)\n")

        w("| mode | ranks | compute (ms) | compute speed-up | efficiency | "
          "comm (ms) | I/O (ms) | end-to-end (ms) | end-to-end speed-up |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|---:|")

        for mode in ("mpi-scatter", "mpi-mpiio"):
            for np_ in sorted(modes.get(mode, {})):
                r = modes[mode][np_]
                comp = num(r["compute_s"])
                comm = num(r["scatter_s"]) + num(r["gather_s"])
                io = num(r["read_s"]) + num(r["write_s"])
                tot = num(r["total_s"])
                sc = num(seq["compute_s"]) / comp if comp else 0.0
                st = num(seq["total_s"]) / tot if tot else 0.0
                w(f"| {mode} | {np_} | {comp*1000:.3f} | {sc:.2f}x | "
                  f"{sc/np_*100:.0f}% | {comm*1000:.2f} | {io*1000:.2f} | "
                  f"{tot*1000:.2f} | {st:.2f}x |")
        w("")

    # A single headline table makes the report's conclusion checkable at a glance.
    w("## Headline: best configuration per resolution\n")
    w("| resolution | best compute speed-up | at | best end-to-end speed-up | at |")
    w("|---|---:|---|---:|---|")
    for res in sorted(by_res, key=lambda s: int(s.split("x")[0])):
        modes = by_res[res]
        seq = modes.get("sequential", {}).get(1)
        if not seq:
            continue
        best_c = best_t = (0.0, "")
        for mode in ("mpi-scatter", "mpi-mpiio"):
            for np_, r in modes.get(mode, {}).items():
                comp, tot = num(r["compute_s"]), num(r["total_s"])
                if comp and num(seq["compute_s"]) / comp > best_c[0]:
                    best_c = (num(seq["compute_s"]) / comp, f"{mode}, np={np_}")
                if tot and num(seq["total_s"]) / tot > best_t[0]:
                    best_t = (num(seq["total_s"]) / tot, f"{mode}, np={np_}")
        w(f"| {res} | {best_c[0]:.2f}x | {best_c[1]} | "
          f"{best_t[0]:.2f}x | {best_t[1]} |")
    w("")

    text = "\n".join(out)
    with open(OUT, "w") as f:
        f.write(text)
    print(text)
    print(f"\n[wrote {OUT}]", file=sys.stderr)


if __name__ == "__main__":
    main()
